# -*- coding: utf-8 -*-
"""Studentdb1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gB8-wEo6OE-n4rqJpiicu2lwJ9dwGukk
"""

import sqlite3

con=sqlite3.connect("students.db")
cursor=con.cursor()

cursor.execute("""
 CREATE TABLE IF NOT EXISTS students (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT, marks INTEGER)""")

con.commit()
print("database ready!")

#MENU FOR STUDENT DATABASE

print("This is a menu driven program:")
while True:
  print("""THE MENU IS AS FOLLOWS:
  1. To enter student's record
  2. To display you records
  3. To update your marks
  4. To find your record
  5. To delete your record
  6. To exit""")

  option=int(input("Enter your option:"))
  if option==1:
    add()
  elif option==2:
    display()
  elif option==3:
    update()
  elif option==4:
    find()
  elif option==5:
    delete()
  elif option==6:
    print("Goodbye!")
    break
  else:
    print("Invaild option, try again")

def add():
  try:
    name=input("Enter your name:")
    if not name.isalpha():
      raise ValueError("Only alphabets, no other characters")
    marks=int(input("Enter your marks:"))
    if marks>600 or marks<0:
      raise ValueError("Marks cannot be negative nor more than six hundred")
    cursor.execute("insert into students (name,marks) values (?,?)",(name,marks))
    con.commit()
    print("Student added")
  except ValueError as e:
    print("Invalid input")

add()

def display():
  cursor.execute("select*from students")
  rows=cursor.fetchall()

  for row in rows:
    print(row)

display()

def update_marks():
  ID=int(input("Enter you ID number:"))
  marks=int(input("Enter the updated marks:"))

  cursor.execute('update students set marks=? where id=?', (marks,ID))
  con.commit()
  print("data updated")

update_marks()

def find():
  name=input("enter the name of the student to find:")
  cursor.execute("select name, marks from students where name=?", (name,))
  result=cursor.fetchall()
  print(result)

find()

def delete():
  ID=int(input("Enter the ID you want to delete:"))

  cursor.execute("delete from students where id=?", (ID,))
  con.commit()

  print("Student info deleted")

delete()

